version: '3'

services:
  postgres:
    container_name: postgres-local-16.0
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data:
    driver: local
